name: pypnp CICD

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: 1
  VENV: .venv

jobs:
  analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: noahnu/.github/.github/actions/setup-python@main

      - name: Lint
        run: poetry run invoke lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [analysis]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: noahnu/.github/.github/actions/setup-python@main

      - name: Build
        run: poetry run invoke build
