name: Manual Release

on:
  workflow_dispatch:

env:
  CI: 1
  VENV: .venv

permissions:
  actions: read
  issues: write
  contents: write
  pull-requests: write

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    environment: release
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_PUBLISH_TOKEN }}
    steps:
      - uses: noahnu/.github/.github/actions/setup-python@main
        with:
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v4.0.0
        with:
          branch: main
          dry_run: false
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
